"""add integrity constraints and indexes

Revision ID: 575c64810fd3
Revises: d8a5daa0264e
Create Date: 2026-04-26 15:11:58.502917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575c64810fd3'
down_revision: Union[str, Sequence[str], None] = 'd8a5daa0264e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_candidate_status', 'applications', ['candidate_user_id', 'status'], unique=False)
    op.create_index('ix_applications_job_status', 'applications', ['job_id', 'status'], unique=False)
    op.create_unique_constraint('uq_applications_job_candidate', 'applications', ['job_id', 'candidate_user_id'])
    op.alter_column('applications', 'status', server_default=sa.text("'SUBMITTED'"))
    op.alter_column('users', 'role', server_default=sa.text("'CANDIDATE'"))
    op.drop_constraint(op.f('candidate_profiles_user_id_fkey'), 'candidate_profiles', type_='foreignkey')
    op.create_foreign_key(
        op.f('candidate_profiles_user_id_fkey'),
        'candidate_profiles',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(op.f('companies_owner_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(
        op.f('companies_owner_user_id_fkey'),
        'companies',
        'users',
        ['owner_user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_owner_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_owner_user_id_fkey'), 'companies', 'users', ['owner_user_id'], ['id'])
    op.drop_constraint(op.f('candidate_profiles_user_id_fkey'), 'candidate_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_profiles_user_id_fkey'), 'candidate_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role', server_default=None)
    op.alter_column('applications', 'status', server_default=None)
    op.drop_constraint('uq_applications_job_candidate', 'applications', type_='unique')
    op.drop_index('ix_applications_job_status', table_name='applications')
    op.drop_index('ix_applications_candidate_status', table_name='applications')
    # ### end Alembic commands ###
