"""add company recruiter memberships

Revision ID: 9ef21ddd8958
Revises: ef3e98b057dc
Create Date: 2026-04-26 12:22:16.245616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ef21ddd8958"
down_revision: Union[str, Sequence[str], None] = "ef3e98b057dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_recruiters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("recruiter_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recruiter_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "recruiter_user_id",
            name="uq_company_recruiter_company_id_recruiter_user_id",
        ),
    )
    op.create_index(
        op.f("ix_company_recruiters_company_id"), "company_recruiters", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_recruiters_recruiter_user_id"),
        "company_recruiters",
        ["recruiter_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_recruiters_recruiter_user_id"), table_name="company_recruiters")
    op.drop_index(op.f("ix_company_recruiters_company_id"), table_name="company_recruiters")
    op.drop_table("company_recruiters")
    # ### end Alembic commands ###
